config/routes.rb
Rails.application.routes.draw do
  root 'welcome#login'

  get 'login', to: "welcome#login", as: 'login'

  post 'signup', to: "welcome#create", as: 'signup'

  post 'login', to: "welcome#attempt_login"

  get 'index', to: "welcome#index", as: 'index'

  get 'logout', to: "welcome#logout"

  scope 'api' do
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :host, :class_name => "User", :foreign_key => "user_id"
  has_many :invites
  has_many :attendees, :through => :invites, :source => :user
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email,
    presence: true,
    uniqueness: true

  has_many :events
  has_many :invites
  has_many :accepted, :through => :invites, :source => :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
respond_to :json

def index
  # For a given controller action,
  # respond_with generates an appropriate
  # response based on the mime-type requested
  # by the client.
  respond_with Event.all
end

def show
  respond_with User.find(params[:id]).events
end

def create
  # respond_with Event.create(params[:eventname, :eventlng, :eventlat, :eventplace])
end

def update

end

def destroy

end

private

def event_params
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :confirm_logged_in, only: [:index]
  before_action :prevent_login_signup, only: [:signup, :login]
  skip_before_action :verify_authenticity_token

  respond_to :json, :html

  def signup
    @user = User.new
  end

  def login
    @user = User.new
  end

  def index
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.create(user_params)
    if @user.save
      #Usermailer
      session[:user_id] = @user.id
      flash[:success] = "You are now logged in!"
      redirect_to index_path
    else
      render :login
    end
  end

  def attempt_login

    if params[:email].present? && params[:password].present?
      found_user = User.where(email: params[:email]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if !found_user
      flash.now[:alert] = "Invalid email"
      render :login

    elsif !authorized_user
      flash.now[:alert] = "Invalid password"
      render :login

    else
      session[:user_id] = authorized_user.id
      flash[:success] = "You are now logged in."
      redirect_to index_path
    end

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to login_path
  end



  private
  def user_params
    params.require(:user).permit(:email, :password, :password_digest)
  end

  def confirm_logged_in
    unless session[:user_id]
      redirect_to login_path, alert: "Please log in"
    end
  end

  def prevent_login_signup
    if session[:user_id]
      redirect_to index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<iframe
  width="100%"
  height="400"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDhGuvGFeKswkwIbXbX0KB8fB_s2nKvu7Y
    &q=City+Hall,New+York+NY">
</iframe>

{{44.55 | currency}}

app/views/layouts/_loginmodal.html.erb
<!-- Login Modal -->
<li><a href="#" data-toggle="modal" data-target=".login-modal">Login</a></li>

<div class="modal fade login-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Log in</h3>
      </div>

      <div class="modal-body">
        <form action="/login" method = "post">
          <p>
            <label for="email">Email:</label><br>
            <input type="email" name="email" id="email" autofocus>
          </p>
          <p>
            <label for="password">Password:</label><br>
            <input type="password" name="password" id="password">
          </p>
          <p>
            <input type="submit" value="Log In" class ="btn ">
          </p>
        </form>
      </div>

      <div class="modal-footer">
        New user?
        <a data-dismiss="modal" data-toggle="modal" data-target=".login-modal">Register here</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Serendipitous</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">About<span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render "layouts/loginmodal" %>
        <%= render "layouts/signupmodal" %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbarloginpage.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Serendipitous</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">About<span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render "layouts/loginmodal" %>
        <%= render "layouts/signupmodal" %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbarmain.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Serendipitous</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">About<span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="glyphicon glyphicon-user"> </span> Welcome, <%= @user.fname %>! </span>
         <ul class="dropdown-menu" role="menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">My Friends</a></li>
            <li><a href="#">My Events</a></li>
            <li class="divider"></li>
            <li><a href="/logout">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_signupmodal.html.erb
<!-- Signup Modal -->
 <li><a href="#" data-toggle="modal" data-target=".signup-modal">Sign up</a></li>

<div class="modal fade signup-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Register </h3>
    </div>
    <div class="modal-body">
      <%= form_for(@user, url: signup_path) do |f|%>
        <p>
          <%= f.label(:fname) %> <br>
          <%= f.text_field(:fname, autofocus: true) %> <br>
        </p>
        <p>
          <%= f.label(:lname) %> <br>
          <%= f.text_field(:lname) %> <br>
        </p>
        <p>
          <%= f.label(:email)%> <br>
          <%= f.email_field(:email)%><br>
          <span>*please ensure your email contains @ symbol</span>
        </p>
        <p>
          <%= f.label(:password) %> <br>
          <%= f.password_field(:password)%><br>
          <span>*please ensure password is 6-30 characters long</span>
        </p>
        <p>
          <%= f.label(:password_confirmation) %> <br>
          <%= f.password_field(:password_confirmation)%><br>
          <span>*please ensure password is 6-30 characters long</span>
        </p>
        <p>
          <%= f.submit("Register", class: "btn" )%>
        </p>
      <% end %>
    </div>
    <div class="modal-footer">
        Already a user?
        <a data-dismiss="modal" data-toggle="modal" data-target=".signup-modal">Sign in here</a>
    </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="serendipitousApp">
<head>
  <title>Serendipitous</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhGuvGFeKswkwIbXbX0KB8fB_s2nKvu7Y"></script>
  <script type="text/javascript" src="/assets/javascripts/map-canvas-geolocation.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/welcome/index.html.erb
<%= render "layouts/navbarmain", locals: {user: @user} %>

<div id="map-canvas" style="width: 100%; height: 50%"></div>

<div>
  <!-- View Tabs  -->
  <view-tabs></view-tabs>
</div>

app/views/welcome/login.html.erb
<%= render "layouts/navbarloginpage" %>